### ISSUE TITLE
Подключить DBUnit

### ISSUE THREAD

**Issue by romach** [Javer-com-ua/FlowerExpert#109]
* [Wiki](https://github.com/Javer-com-ua/WIKI/wiki/%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-DbUnit)

***

* [Тестирование в Java. JUnit](http://habrahabr.ru/post/120101/)
* [JUnit & Spring – What You Don’t Know](http://gordondickens.com/wordpress/2011/01/07/junit-spring-what-you-dont-know-about/comment-page-1/)

***

* [@RunWith](http://junit.sourceforge.net/javadoc/org/junit/runner/RunWith.html) - определяет, с помощью какого класса будет выполнен тест.
* [@ContextConfiguration](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/test/context/ContextConfiguration.html) - определяет контекст для тестов.

**Comment by romach** [comment]
- [ ] Исправить ошибку `No bean named 'transactionManager'`

**Comment by AnatoliiStepaniuk** [comment]
reset autoincrement by static method 
http://www.petrikainulainen.net/programming/spring-framework/spring-from-the-trenches-resetting-auto-increment-columns-before-each-test-method/
