### ISSUE TITLE
Подключить Hibernate

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [Javer-com-ua/FlowerExpert#119]

**Comment by romach** [comment]
Информация по Hibernate

**Статьи**

* [Spring MVC 3, Аннотации Hibernate, MySQL. Туториал по интеграции](http://habrahabr.ru/post/248541/)
* [Spring — Hibernate: ассоциация один ко многим](http://habrahabr.ru/post/249073/)

**Книги**

* [Just Hibernate](https://it-ebooks.info/book/3524/)

**Comment by AnatoliiStepaniuk** [comment]
http://www.codejava.net/frameworks/spring/spring-4-and-hibernate-4-integration-tutorial-part-2-java-based-configuration

**Comment by romach** [comment]
:video_camera: Видео:
* [ Config](http://www.youtube.com/watch?v=_wsN58yk_WE)
* [Mapping](http://www.youtube.com/watch?v=ZhRt5fwEi0s)
* [Query](http://www.youtube.com/watch?v=2faPicW-xbg)

**Comment by AnatoliiStepaniuk** [comment]
One-To-Many  - можем использовать для UserChoice
http://www.codejava.net/frameworks/hibernate/hibernate-one-to-many-association-on-join-table-annotations-example

**Comment by romach** [comment]
* [Hibernate Many To Many Annotation Mapping Tutorial](http://viralpatel.net/blogs/hibernate-many-to-many-annotation-mapping-tutorial/)
* [Hibernate @ManyToMany Unidirectional and Bidirectional](https://howtoprogramwithjava.com/hibernate-manytomany-unidirectional-bidirectional/)
* [Chapter 7. Collection mapping](https://docs.jboss.org/hibernate/orm/4.3/manual/en-US/html/ch07.html)

**Comment by romach** [comment]
* [Spring 4 and Hibernate 4 Integration Tutorial Part 1: XML Configuration](http://www.codejava.net/frameworks/spring/spring-4-and-hibernate-4-integration-tutorial-part-1-xml-configuration)

**Comment by AnatoliiStepaniuk** [comment]
spring 4 + hibernate many-to-many

**Comment by romach** [comment]
[Spring 4 MVC+Hibernate 4+MySQL+Maven integration + Testing example using annotations](http://websystique.com/springmvc/spring-4-mvc-and-hibernate4-integration-testing-example-using-annotations/)

**Comment by romach** [comment]
[Converter](http://www.thoughts-on-java.org/jpa-21-how-to-implement-type-converter/)
