### ISSUE TITLE
Убираем методы типа existsColor()?

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [Javer-com-ua/FlowerExpert#121]
Сейчас я добавляю специальные entity INVALID_COLOR, INVALID_TEMPER, INVALID_MESSAGE, которые будут возвращаться из методов наподобие ColorsDaoJdbcTemplate.getColorById(int) если в базе не найден такой элемент (раньше у нас возвращался просто null, что нехорошо). В таком случае, есть ли необходимость в методах вроде existsColor(), existsCity() и пр. если мы можем просто проверять, равняется ли полученный объект из метода getColorById(int) объекту INVALID_COLOR?

**Comment by romach** [comment]
Использовать `INVALID_` в методах `exists`
