### ISSUE TITLE
Вынести INVALID_CITY из dao в service?

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [Javer-com-ua/FlowerExpert#130]
Может стоит оставить в dao только простые операции, как например получить город по id из базы. А уже остальную логику (например вернуть INVALID_CITY если получили из базы null или произошел exception) поместить в сервис? Если подключим Hibernate, то класс CityDaoJdbcTemplate вообще не будет использоваться - хочу вынести из него то, что может нам еще пригодиться.

**Comment by romach** [comment]
Вообще, это задача дао работать с базой. Не думаю, что нужно в сервис переносить.

**Comment by AnatoliiStepaniuk** [comment]
Верно. Пусть Дао только с базой и работает. А у нас сейчас если дао не может получить объект из базы по заданному ID, то он возвращает INVALID_объект:

    public City getCityById(int id) {
		MapSqlParameterSource params = new MapSqlParameterSource("id", id);
		City city = null;
		try {
			city = jdbcTemplate.queryForObject("select * from cities where id = :id",
					params, new CityRowMapper());
		} catch (DataAccessException e) {
            logger.error("INVALID_CITY", e);
            return City.INVALID_CITY;
		}
		return city;
	}

Это уже бизнес-логика, как поступать в случае если не нашли объект в базе. Думаю, ДАО должен только попытаться получить объект из базы. Если не удается - это уже пусть решает сервис. Предлагаю такой код:

     public City getCityById(int id) {
		MapSqlParameterSource params = new MapSqlParameterSource("id", id);
		City city = jdbcTemplate.queryForObject("select * from cities where id = :id",
					params, new CityRowMapper());
		return city;
	}

А уже сервис пускай ловит DataAccessException, логирует и возвращает INVALID_CITY

**Comment by romach** [comment]
Хорошо, давай так сделаем
