### ISSUE TITLE
Написать тест для метода  create() FlowersService.java

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [Javer-com-ua/FlowerExpert#28]
Заодно можно его и переименовать, чтобы было понятно, что этот метод записывает букет в базу.

**Comment by AnatoliiStepaniuk** [comment]
Неверно считается last_flower_id() в тесте - присваивается значение 0

**Comment by AnatoliiStepaniuk** [comment]
done - ce3efa093d2fd9d8996b19dfcf98a47a3a2e44a9

**Comment by romach** [comment]
done better - 54f59bc87fc9de5995028a7050a8f19f67598223
