### ISSUE TITLE
Не отображается название цветка в кириллице

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [Javer-com-ua/FlowerExpert#3]
Не отображается название цветка в кириллице: Вот пример страницы docreate:

Flower created!
Flower [name=Ð Ð¾Ð¼Ð°ÑÐºÐ°, color1=yellow, color2=yellow, humour=true, tenderness=true, wisdom=true, modesty=false, sociable=false, mystery=false, pride=false, careless=false, pure=false, passion=false, trust=false, love=false, flirt=true, neutral=true]

**Comment by AnatoliiStepaniuk** [comment]
Done.

**Comment by romach** [comment]
Как ты решил проблему?

**Comment by AnatoliiStepaniuk** [comment]
Добавил encoding filter в web.xml. Вот коммит - 24159cd1518afec52e010c6d0a52066f5508c355

П.С. Думаю, нужно для каждого закрытого issue добавлять коммит, в котором этот issue решен.

**Comment by romach** [comment]
Лучше в сообщении коммита писать номер issue, например: issue3 Added UTF-8 encoding to forms

**Comment by AnatoliiStepaniuk** [comment]
Ок! Можно и так, и так :-)

**Comment by AnatoliiStepaniuk** [comment]
Проблема решена не полностью. С помощью фильтра удалось передавать в спринге строку закодированную utf-8, но в базу данных по прежнему пишется неправильно. Вот результат считывания из базы данных:

ID: 8
Name: ??????? ???
Color1: red
Color2: red
Character:
humour 	tenderness 	wisdom 	modesty 	sociable 	mystery 	pride 	careless
true 	true 	false 	false 	false 	false 	false 	false
Message:
pure 	passion 	trust 	love 	flirt 	neutral
true 	true 	false 	false 	false 	false

**Comment by AnatoliiStepaniuk** [comment]
Разобрались. Вот страница на [Вики](https://github.com/Javer-com-ua/WIKI/wiki/%D0%9A%D0%BE%D0%B4%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0-UTF-8-%D0%B4%D0%BB%D1%8F-%D0%B1%D0%B0%D0%B7%D1%8B-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85)
