### ISSUE TITLE
HTTP Status 400 - если не выбран хотя бы один checkbox из каждой группы

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [Javer-com-ua/FlowerExpert#33]
Если не выбрать хотя бы один Color, Temper или Message - выдает такую ошибку. Если Пустое имя - все равно создает букет.

**Comment by aquariusmaster** [comment]
В сигнатуру метода в контроллере добавить параметр BindingResult result. то позволит обрабатывать такую ошибку в контроллере:
@RequestMapping(value = "/createflower", method = RequestMethod.POST)
    public String doCreate(Model model, @ModelAttribute("flower") Flower flower, BindingResult result){
        if (result.hasErrors()){
        	return "error";
        }
    	flowersService.insertFlowerIntoDB(flower);
        model.addAttribute("flower", flower);
        return "flowercreated";
    }
