### ISSUE TITLE
Составить диаграмму для базы данных

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [Javer-com-ua/FlowerExpert#4]
Диаграмму можно прикрепить прямо к этому issue. Когда согласуем ее - создадим для нее страницу в Wiki проекта.

**Comment by Log1c** [comment]
![image](https://cloud.githubusercontent.com/assets/5446405/9001943/ae9603ec-3766-11e5-9d71-f17dba33581e.png)

**Comment by Log1c** [comment]
Как посмотреть:
1. http://ondras.zarovi.cz/sql/demo/
2. Save/Load -> Load XML и вводим xml

<?xml version="1.0" encoding="utf-8" ?>


<sql>
<datatypes db="mysql">
	<group label="Numeric" color="rgb(238,238,170)">
		<type label="Integer" length="0" sql="INTEGER" quote=""/>
	 	<type label="TINYINT" length="0" sql="TINYINT" quote=""/>
	 	<type label="SMALLINT" length="0" sql="SMALLINT" quote=""/>
	 	<type label="MEDIUMINT" length="0" sql="MEDIUMINT" quote=""/>
	 	<type label="INT" length="0" sql="INT" quote=""/>
		<type label="BIGINT" length="0" sql="BIGINT" quote=""/>
		<type label="Decimal" length="1" sql="DECIMAL" re="DEC" quote=""/>
		<type label="Single precision" length="0" sql="FLOAT" quote=""/>
		<type label="Double precision" length="0" sql="DOUBLE" re="DOUBLE" quote=""/>
	</group>

	<group label="Character" color="rgb(255,200,200)">
		<type label="Char" length="1" sql="CHAR" quote="'"/>
		<type label="Varchar" length="1" sql="VARCHAR" quote="'"/>
		<type label="Text" length="0" sql="MEDIUMTEXT" re="TEXT" quote="'"/>
		<type label="Binary" length="1" sql="BINARY" quote="'"/>
		<type label="Varbinary" length="1" sql="VARBINARY" quote="'"/>
		<type label="BLOB" length="0" sql="BLOB" re="BLOB" quote="'"/>
	</group>

	<group label="Date &amp; Time" color="rgb(200,255,200)">
		<type label="Date" length="0" sql="DATE" quote="'"/>
		<type label="Time" length="0" sql="TIME" quote="'"/>
		<type label="Datetime" length="0" sql="DATETIME" quote="'"/>
		<type label="Year" length="0" sql="YEAR" quote=""/>
		<type label="Timestamp" length="0" sql="TIMESTAMP" quote="'"/>
	</group>
	
	<group label="Miscellaneous" color="rgb(200,200,255)">
		<type label="ENUM" length="1" sql="ENUM" quote=""/>
		<type label="SET" length="1" sql="SET" quote=""/>
		<type label="Bit" length="0" sql="bit" quote=""/>
	</group>
</datatypes><table x="467" y="230" name="dicFlowers">
<row name="id" null="1" autoincrement="1">
<datatype>INTEGER</datatype>
<default>NULL</default></row>
<row name="name" null="0" autoincrement="0">
<datatype>VARCHAR</datatype>
<default>'NULL'</default></row>
<key type="PRIMARY" name="">
<part>id</part>
</key>
</table>
<table x="523" y="22" name="dicCharacters">
<row name="id" null="1" autoincrement="1">
<datatype>INTEGER</datatype>
<default>NULL</default></row>
<row name="name" null="0" autoincrement="0">
<datatype>VARCHAR</datatype>
<default>'NULL'</default></row>
<key type="PRIMARY" name="">
<part>id</part>
</key>
</table>
<table x="536" y="125" name="dicFeelings">
<row name="id" null="1" autoincrement="1">
<datatype>INTEGER</datatype>
<default>NULL</default></row>
<row name="name" null="0" autoincrement="0">
<datatype>VARCHAR</datatype>
<default>'NULL'</default></row>
<key type="PRIMARY" name="">
<part>id</part>
</key>
</table>
<table x="60" y="283" name="rules">
<row name="id" null="1" autoincrement="1">
<datatype>INTEGER</datatype>
<default>NULL</default></row>
<row name="flower_id" null="0" autoincrement="0">
<datatype>INTEGER</datatype>
<default>NULL</default><relation table="dicFlowers" row="id" />
</row>
<row name="colorFirst_id" null="0" autoincrement="0">
<datatype>INTEGER</datatype>
<default>NULL</default><relation table="dicColor" row="id" />
</row>
<row name="colorSecond_id" null="1" autoincrement="0">
<datatype>INTEGER</datatype>
<default>NULL</default><relation table="dicColor" row="id" />
</row>
<key type="PRIMARY" name="">
<part>id</part>
</key>
</table>
<table x="968" y="293" name="answers">
<row name="id" null="1" autoincrement="1">
<datatype>INTEGER</datatype>
<default>NULL</default><relation table="answers2feelings" row="answer_id" />
</row>
<row name="user_id" null="0" autoincrement="0">
<datatype>INTEGER</datatype>
<default>NULL</default><relation table="users" row="id" />
</row>
<row name="colorFirst_id" null="1" autoincrement="0">
<datatype>INTEGER</datatype>
<default>NULL</default><relation table="dicColor" row="id" />
</row>
<row name="colorSecond_id" null="0" autoincrement="0">
<datatype>INTEGER</datatype>
<default>NULL</default><relation table="dicColor" row="id" />
</row>
<key type="PRIMARY" name="">
<part>id</part>
</key>
</table>
<table x="646" y="232" name="users">
<row name="id" null="1" autoincrement="1">
<datatype>INTEGER</datatype>
<default>NULL</default></row>
<row name="name" null="1" autoincrement="0">
<datatype>VARCHAR</datatype>
<default>NULL</default></row>
<key type="PRIMARY" name="">
<part>id</part>
</key>
</table>
<table x="539" y="368" name="dicColor">
<row name="id" null="1" autoincrement="1">
<datatype>INTEGER</datatype>
<default>NULL</default></row>
<row name="name" null="0" autoincrement="0">
<datatype>VARCHAR</datatype>
<default>'NULL'</default></row>
<key type="PRIMARY" name="">
<part>id</part>
</key>
</table>
<table x="766" y="16" name="answers2characters">
<row name="answer_id" null="0" autoincrement="0">
<datatype>INTEGER</datatype>
<default>NULL</default><relation table="answers" row="id" />
</row>
<row name="character_id" null="1" autoincrement="0">
<datatype>INTEGER</datatype>
<default>NULL</default><relation table="dicCharacters" row="id" />
</row>
<key type="PRIMARY" name="">
<part>answer_id</part>
<part>character_id</part>
</key>
</table>
<table x="780" y="132" name="answers2feelings">
<row name="answer_id" null="0" autoincrement="0">
<datatype>INTEGER</datatype>
<default>NULL</default></row>
<row name="feelings_id" null="0" autoincrement="0">
<datatype>INTEGER</datatype>
<default>NULL</default><relation table="dicFeelings" row="id" />
</row>
<key type="PRIMARY" name="">
<part>answer_id</part>
<part>feelings_id</part>
</key>
</table>
<table x="297" y="135" name="rules2feelings">
<row name="rule_id" null="0" autoincrement="0">
<datatype>INTEGER</datatype>
<default>NULL</default><relation table="rules" row="id" />
</row>
<row name="feeling_id" null="0" autoincrement="0">
<datatype>INTEGER</datatype>
<default>NULL</default><relation table="dicFeelings" row="id" />
</row>
<key type="PRIMARY" name="">
<part>rule_id</part>
<part>feeling_id</part>
</key>
</table>
<table x="291" y="21" name="rules2character">
<row name="rule_id" null="0" autoincrement="0">
<datatype>INTEGER</datatype>
<default>NULL</default><relation table="rules" row="id" />
</row>
<row name="character_id" null="0" autoincrement="0">
<datatype>INTEGER</datatype>
<default>NULL</default><relation table="dicCharacters" row="id" />
</row>
<key type="PRIMARY" name="">
<part>rule_id</part>
<part>character_id</part>
</key>
</table>
</sql>

**Comment by AnatoliiStepaniuk** [comment]
Все-таки эта диаграмма сложновата. Давайте начнем со схемы, которую обсуждали вчера (без правил и пользователей):
1. Таблица Flowers (flower_id, flower_name, color1, color2)
2. Таблица Flowers2Characters(flower_id, character_id)
3. Таблица Flowers2Messages(flower_id, message_id)
4. Таблица dicCharacters (как на схеме)
5. Таблица dicMessages (аналогично)

По поводу скорости поиска в таблицах Flowers2Characters и Flowers2Messages, там действительно наверное все оптимизировано, так что поиск не должен быть сильно длинным.
