### ISSUE TITLE
Настроить Deploy в pom.xml

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [Javer-com-ua/FlowerExpert#5]
Избавиться от необходимости копирования .war файла.

**Comment by AnatoliiStepaniuk** [comment]
Done - a9e0a6d13739ae2f4b2052a005e4d993c4fcff12

**Comment by romach** [comment]
А что делать тому, у кого Windows или томкат не там установлен?

**Comment by AnatoliiStepaniuk** [comment]
Договорились пока закомментировать код переноса файла .war в папку webapps Томкэта. Возможно, потом это все будет делать Jenkins. Коммит - c8c0aa30bc47d5f5258a45a8e09ae065f89fa48c
