### ISSUE TITLE
Добавить в класс Flower поля price, city и url.

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [Javer-com-ua/FlowerExpert#62]

**Comment by romach** [comment]
Предлагаю добавить поля:
* price (int)
* city (String)
* imageUrl (String)
* sellerUrl(String)

**Comment by AnatoliiStepaniuk** [comment]
Мне кажется, что логично город вынести в отдельный класс (с полем String). Один и тот же город мы будем использовать много раз в разных букетах. Плюс будем проводить поиск по букетам. Про остальные поля согласен!

**Comment by AnatoliiStepaniuk** [comment]
- [ ] Добавить поля в класс
- [ ] Добавить в таблицу
