### ISSUE TITLE
Убрать методы hashCode() и equals() из Flower

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [Javer-com-ua/FlowerExpert#7]
Нужно найти способ убрать эти методы - сильно загромождают код. Должен быть способ, чтобы они вызывались неявно, без указания в коде.

**Comment by romach** [comment]
Их можно переписать, но убирать нельзя, потому что в таком случае при сравнении двух объектов постоянно будет возвращаться false.

**Comment by AnatoliiStepaniuk** [comment]
Согласен, оставляем как есть.
