### ISSUE TITLE
Изменить структуру папок

### ISSUE THREAD

**Issue by romach** [Javer-com-ua/FlowerExpert#9]
Изменить структуру папок проекта согласно стандартным рекомендациям: https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

**Comment by AnatoliiStepaniuk** [comment]
Как раз начал это делать, чтобы было куда тесты поместить :smile:

**Comment by AnatoliiStepaniuk** [comment]
Рома изменил структуру в коммите - aaef053bc266dbd893d69177b06994e23440db88
