### ISSUE TITLE
Template для JSP

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [Javer-com-ua/FlowerExpert#92]
Добавить в layouts:
- [ ] Header
- [ ] Scripts

**Comment by romach** [comment]
* [Tutorial: Thymeleaf + Spring](http://www.thymeleaf.org/doc/tutorials/2.1/thymeleafspring.html)
* [Thymeleaf Spring MVC Integration Example](http://www.furkanzumrut.com/thymeleaf-spring-mvc-integration-example)
* [Thymeleaf integration with Spring (Part 1)](http://xpadro.blogspot.com/2014/02/thymeleaf-integration-with-spring-part-1.html)
* [Spring MVC part III: ThymeLeaf integration](https://doanduyhai.wordpress.com/2012/04/14/spring-mvc-part-iii-thymeleaf-integration/)
